# Generated by Django 6.1.1 on 2026-10-02 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Сумма')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='ExpensePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='expenses/%Y/%m/%d/', verbose_name='Фотография')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.expenses', verbose_name='Расход')),
            ],
            options={
                'verbose_name': 'Фотография расхода',
                'verbose_name_plural': 'Фотографии расхода',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('day', 'День'), ('night', 'Ночь')], default='day', max_length=5, verbose_name='Смена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('cards', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Безнал')),
                ('spb', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='СБП')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Наличные')),
                ('remaining_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Остаток наличных')),
                ('encashment', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Инкассация')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/%d/', verbose_name='Фотография')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.report', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Фотография отчёта',
                'verbose_name_plural': 'Фотографии отчёта',
            },
        ),
    ]
