# Generated by Django 6.1.1 on 2026-09-28 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('warranty_until', models.DateTimeField(blank=True, null=True, verbose_name='Гарантия до')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('cpu', models.CharField(max_length=255, verbose_name='Процессор')),
                ('gpu', models.CharField(max_length=255, verbose_name='Видеокарта')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('storage', models.CharField(max_length=255, verbose_name='Хранилище')),
                ('warranty_until', models.DateTimeField(blank=True, null=True, verbose_name='Гарантия до')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('devicebasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computers.devicebasemodel')),
            ],
            bases=('computers.devicebasemodel',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('devicebasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computers.devicebasemodel')),
            ],
            bases=('computers.devicebasemodel',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('devicebasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computers.devicebasemodel')),
            ],
            bases=('computers.devicebasemodel',),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер ПК')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.pc')),
                ('keyboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.keyboard')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.monitor')),
                ('mouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.mouse')),
            ],
        ),
    ]
